name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
         
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.9
        
        -   name: Install dependencies
            run: |
                pip install pytest
        
        # -   name: Run pytest
        #     run: |
        #         pytest 

        
        - name: Find modified Python files
          id: find_files
          run: |
            echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)"
        
        - name: Run pytest on modified files
          run: |
            pytest ${{ steps.find_files.outputs.files }}
