name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4          
#          with:
#            token: ${{ secrets.PAT }}
#            fetch-depth: 2
         
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.9
            cache: 'pip' # caching pip dependencies
            

        # - name: Debug file permissions
        #   run: |
        #         ls -l Utilities/esop/esop_static_linux.exe
        #         file Utilities/esop/esop_static_linux.exe

        - name: Set executable permissions
          run: chmod +x Utilities/esop/esop_static_linux.exe
          
        # - name: Print file permissions
        #   run: ls -l Utilities/esop/esop_static_linux.exe



        - name: Run executable
          run: Utilities/esop/esop_static_linux.exe 3 e8

        
        - name: Install dependencies
          run: |
                pip install pytest
                pip install -r requirements.txt

        
        - name: Run pytest
          run: |
                pytest 

        
        # -   name: Find modified Python files
        #     id: find_files
        #     run: |
                # echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)" >> $GITHUB_STATE
      
                
        # -   name: Print Modified Files
        #     run: |
        #         echo "${{ steps.find_files.outputs.files }}"

#        -   name: Find Modified Files
#            id: find_files
#            run: |
#                echo "git diff --name-only ${{ github.event.before }} ${{ github.sha }} "
#                echo "git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true"
#                echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)"
#        #        echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)" >> $GITHUB_STATE
#
#
#        -   name: Print Modified Files
#            run: |
#                echo "Modified Python files:"                
#                echo "${{ steps.find_files.outputs.files }}"
#        #        cat $GITHUB_STATE
#
#
#        -   name: Run pytest on modified files
#            run: |
#                pytest ${{ steps.find_files.outputs.files }} 
#            #$GITHUB_STATE
